### ISSUE TITLE
error: Could not load plugin ... libpdf-mupdf.so: undefined symbol: fz_page_label

### ISSUE THREAD

**Issue by ddmin** [pwmt/zathura-pdf-mupdf#67]
Ubuntu 22.04 x86_64 GNU/Linux

zathura 0.5.6
zathura-pdf-mupdf 0.4.2
mupdf 1.24.2

I'm getting this error when trying to use this plugin with zathura.

```
error: Could not load plugin '/usr/local/lib/x86_64-linux-gnu/zathura/libpdf-mupdf.so' (/usr/local/lib/x86_64-linux-gnu/zathura/libpdf-mupdf.so: undefined symbol: fz_page_label).
error: Found no plugins. Please install at least one plugin.
info: Opening plain database via sqlite backend.
warning: sqlite database already exists. Set your database backend to sqlite
error: Could not determine file type.
```

[(zathura)-install-log.txt](https://github.com/pwmt/zathura-pdf-mupdf/files/15371697/zathura.-install-log.txt)
[(zathura)-meson-log.txt](https://github.com/pwmt/zathura-pdf-mupdf/files/15371698/zathura.-meson-log.txt)
[(zathura-pdf-mupdf)-install-log.txt](https://github.com/pwmt/zathura-pdf-mupdf/files/15371699/zathura-pdf-mupdf.-install-log.txt)
[(zathura-pdf-mupdf)-meson-log.txt](https://github.com/pwmt/zathura-pdf-mupdf/files/15371702/zathura-pdf-mupdf.-meson-log.txt)

**Comment by sebastinas** [comment]
Not sure how you managed to build it, since it should have failed with an implicit function declaration. In any case, your mupdf insallation is too old. You need 1.24 or newer.

**Comment by sebastinas** [comment]
06be8e6 will make sure that this does not happen in the future.

**Comment by abhijithanandan** [comment]
I face the same issue on Ubuntu.
@sebastinas, why did you mention the mupdf version is old when he has mentioned the version as mupdf 1.24.2? 
I also tried by building latest mupdf 1.24.3 from source.
But my meson build failed with the same error. 
meson says it cannot find libpdf-mupdf.so

**Comment by sebastinas** [comment]
> I face the same issue on Ubuntu. @sebastinas, why did you mention the mupdf version is old when he has mentioned the version as mupdf 1.24.2? I also tried after building latest mupdf 1.24.3 from source. But my meson build failed with the same error. meson says it cannot find libpdf-mupdf.so

I guess I misread. If `fz_page_ label` is missing and the mupdf version s 1.24.3, there is something wrong with mupdf installation.

> 
> Below is the output of `meson build` command
> 
> ```shell
> The Meson build system
> Version: 1.4.1
> Source dir: /home/sps/ProgramFiles/pwmt/zathura-pdf-mupdf
> Build dir: /home/sps/ProgramFiles/pwmt/zathura-pdf-mupdf/build
> Build type: native build
> Project name: zathura-pdf-mupdf
> Project version: 0.4.3
> C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
> C linker for the host machine: cc ld.bfd 2.38
> Host machine cpu family: x86_64
> Host machine cpu: x86_64
> Found pkg-config: YES (/usr/bin/pkg-config) 1.8.0
> Run-time dependency zathura found: YES 0.5.6
> Run-time dependency girara-gtk3 found: YES 0.4.4
> Run-time dependency glib-2.0 found: YES 2.72.4
> Run-time dependency cairo found: YES 1.16.0
> Found CMake: /usr/bin/cmake (3.22.1)
> Run-time dependency mupdf found: NO (tried pkgconfig and cmake)
> Library mupdf-third found: YES
> Has header "mupdf/fitz/version.h" : YES 
> Has header "mupdf/fitz.h" : YES 
> Has header "mupdf/pdf.h" : YES 
> Library mupdf found: YES
> Compiler for C supports arguments -Werror=implicit-function-declaration: YES 
> Compiler for C supports arguments -Werror=vla: YES 
> Build targets in project: 1
> 
> Found ninja-1.10.1 at /usr/bin/ninja
> WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
> ```
> 
> It has not found run-time dependency mupdf
> 
> Later, when I try `ninja` from build directory, I get the following error:
> 
> ```shell
> [1/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_plugin.c.o
> [2/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_select.c.o
> [3/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_page.c.o
> [4/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_utils.c.o
> [5/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_index.c.o
> [6/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_document.c.o
> [7/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_render.c.o
> [8/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o
> [9/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_image.c.o
> [10/11] Compiling C object libpdf-mupdf.so.p/zathura-pdf-mupdf_links.c.o
> [11/11] Linking target libpdf-mupdf.so
> FAILED: libpdf-mupdf.so 
> cc  -o libpdf-mupdf.so libpdf-mupdf.so.p/zathura-pdf-mupdf_document.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_image.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_index.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_links.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_page.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_plugin.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_render.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_search.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_select.c.o libpdf-mupdf.so.p/zathura-pdf-mupdf_utils.c.o -Wl,--as-needed -Wl,--allow-shlib-undefined -shared -fPIC -Wl,-rpath,/usr/local/lib/x86_64-linux-gnu -Wl,-rpath-link,/usr/local/lib/x86_64-linux-gnu -Wl,--start-group /usr/local/lib/x86_64-linux-gnu/libgirara-gtk3.so /usr/lib/x86_64-linux-gnu/libgtk-3.so /usr/lib/x86_64-linux-gnu/libgdk-3.so /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so /usr/lib/x86_64-linux-gnu/libpango-1.0.so /usr/lib/x86_64-linux-gnu/libharfbuzz.so /usr/lib/x86_64-linux-gnu/libatk-1.0.so /usr/lib/x86_64-linux-gnu/libcairo-gobject.so /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so /usr/lib/x86_64-linux-gnu/libgio-2.0.so /usr/lib/x86_64-linux-gnu/libgobject-2.0.so /usr/lib/x86_64-linux-gnu/libglib-2.0.so /usr/lib/x86_64-linux-gnu/libcairo.so -lmupdf -lmupdf-third -Wl,--end-group
> /usr/bin/ld: /usr/local/lib/libmupdf-third.a(parser.o): warning: relocation against `kGumboEmptySourcePosition' in read-only section `.text.handle_in_body'
> /usr/bin/ld: /usr/local/lib/libmupdf.a(device.o): relocation R_X86_64_PC32 against symbol `fz_unit_rect' can not be used when making a shared object; recompile with -fPIC
> /usr/bin/ld: final link failed: bad value
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.
> ```

As the error is saying: rebuild mupdf with `-fPIC`

> I cannot locate `libdf-mupdf.so` anywhere in the `mupdf` source distribution which I downloaded from the [release page](https://mupdf.com/releases?utm_source=rtd-mupdf&utm_medium=rtd&utm_content=inline-link&_gl=1*1d7dygq*_ga*MTIzNDQxMjU0Ny4xNzE4Mjc4NTE4*_ga_JZTN4VTL9M*MTcxODI3ODUxNy4xLjEuMTcxODI5NDIxOC42MC4wLjA.)

Of course not, because `libpdf-mupdf.so` is the product of building `zathura-pdf-mupdf`.
