### ISSUE TITLE
Zathura Crashes and Closes while Scrolling the Document 

### ISSUE THREAD

**Issue by Mash-em** [pwmt/zathura-pdf-mupdf#68]
![swappy-20240525_135150](https://github.com/pwmt/zathura/assets/169830207/4f2a4394-922d-4b83-aa01-3d8c39bfea2b)

**Comment by user202729** [comment]
I raise the issue on mupdf server, and maybe one reason is violation of threading rules.

https://bugs.ghostscript.com/show_bug.cgi?id=707809

**Comment by user202729** [comment]
Seems the issue is closed already, but not sure if it's related:  https://github.com/pwmt/zathura/commit/1d398dfaf08e77c2ebe0b76a696c3be26da69328
