### ISSUE TITLE
meson.build / README dependency mismatch

### ISSUE THREAD

**Issue by rndxelement** [pwmt/zathura-pdf-mupdf#73]
Greetings,

I'm wondering whether leptonica and tesseract are still required build dependencies.
In Gentoo we currently exclude them from the list of required build dependencies.

The README lists only a few of the build dependencies acutally required in `meson.build`.
In `meson.build` there's also e.g. gumbo, tesseract, leptonica, cairo.

So it seems to be that either the README is a bit outdated (or doesn't list all build deps on purpose)
or the list of builds dependencies in `meson.build` includes dependencies that aren't actually required.

Is this a misunderstanding or an actual incoherence?

P.S. we also exclude mupdfthird, however this could be Gentoo-only thing.

Thanks and keep up the good work. I love zathura-pdf-mupdf.

**Comment by sebastinas** [comment]
They are still required when building with Debian's `mupdf` packaging. I don't know if it has any use for Gentoo's packaging. But current linkers (potentially with the correct flags) will make sure that no unused libraries will be linked into the final binary.

**Comment by rndxelement** [comment]
Ah, alright, thanks!
